version: 2
updates:

  - package-ecosystem: "nuget"
    directory: "/" # Location of package manifests
    schedule:
      day: "sunday"
      interval: "weekly"
    assignees:
      - "cdschneider"
    reviewers:
      - "cdschneider"

  - package-ecosystem: "github-actions"
    directory: "/" # Location of package manifests
    schedule:
      day: "sunday" 
      interval: "weekly"
    assignees:
      - "cdschneider"
    reviewers:
      - "cdschneider"
