version = 0.1
[default.global.parameters]
region = "us-east-1"

[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "aws-access-key-expiry"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1e89st9r1pcd9"
s3_prefix = "aws-access-key-expiry"
confirm_changeset = false
fail_on_empty_changeset = false
force_upload = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
tags = "App=\"aws-access-key-expiry\""
image_repositories = ["AccessKeyRotationFunction=892601359836.dkr.ecr.us-east-1.amazonaws.com/awsaccesskeyexpirya3e3c7e1/accesskeyrotationfunctionb8c41863repo", "AccessKeyActionsFunction=892601359836.dkr.ecr.us-east-1.amazonaws.com/awsaccesskeyexpirya3e3c7e1/accesskeyactionsfunction9a31ded0repo"]

[default.package]
[default.package.parameters]
s3_bucket = "cdschneid-sam-artifacts"
s3_prefix = "aws-access-key-expiry"
output_template_file = "packaged.yaml"
force_upload = true

[default.publish]
[default.publish.parameters]
template_file = "packaged.yaml"
