AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  aws-access-key-expiry

  Sample SAM Template for aws-access-key-expiry

Resources:
  ExpireAccessKeysStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      DefinitionUri: statemachine/workflow.asl.json
      DefinitionSubstitutions:
        StatesDateTimeAddArn: !GetAtt StatesDateTimeAddFunction.Arn
      Type: EXPRESS
      Tracing:
        Enabled: True
      Logging:
        Destinations:
          - CloudWatchLogsLogGroup:
              LogGroupArn: !GetAtt ExpireAccessKeysStateMachineLogGroup.Arn
        IncludeExecutionData: True
        Level: ALL
      Events:
        RecurringScheduleV2:
          Type: ScheduleV2
          Properties:
            ScheduleExpression: "rate(5 minutes)"
            State: ENABLED
      Policies:
        - IAMReadOnlyAccess
        - !Ref IAMUpdateAccessKeysPolicy
        - !Ref StepFunctionsTracingPolicy
        - !Ref StepFunctionsLoggingPolicy
        - LambdaInvokePolicy:
            FunctionName: !Ref StatesDateTimeAddFunction

  ExpireAccessKeysStateMachineLogGroup:
    Type: AWS::Logs::LogGroup

  StatesDateTimeAddFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src/States.DateTimeAdd/
      Handler: States.DateTimeAdd::States.DateTimeAdd.Function::FunctionHandler
      Runtime: dotnet6
      Architectures:
        - x86_64
   
  StepFunctionsLoggingPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - 'logs:CreateLogDelivery'
              - 'logs:GetLogDelivery'
              - 'logs:UpdateLogDelivery'
              - 'logs:DeleteLogDelivery'
              - 'logs:ListLogDeliveries'
              - 'logs:PutResourcePolicy'
              - 'logs:DescribeResourcePolicies'
              - 'logs:DescribeLogGroups'
            Resource: '*'

  StepFunctionsTracingPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - 'xray:PutTraceSegments'
              - 'xray:PutTelemetryRecords'
              - 'xray:GetSamplingRules'
              - 'xray:GetSamplingTargets'
            Resource: '*'

  IAMUpdateAccessKeysPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - 'iam:UpdateAccessKey'
            Resource: '*'