name: build

on:
  push:
    branches: [ main, github-actions ]
  pull_request:
    branches: [ main ]
    
env:
  AWS_REGION : "us-east-1"

jobs:
  sam-build:
    
    runs-on: ubuntu-latest
    permissions:
      id-token: write   # This is required for requesting the JWT
      contents: read    # This is required for actions/checkout

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.8'
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'
      - uses: aws-actions/setup-sam@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-duration-seconds: 900
          role-to-assume: arn:aws:iam::892601359836:role/github-action-role
          aws-region: ${{ env.AWS_REGION }}
      - run: sam validate
      - run: sam build --debug
  
  dotnet-build:
    
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [ '6.0.x' ]
        configuration: ['Debug', 'Release']

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Restore tools
        run: dotnet tool restore -v n
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build -c ${{ matrix.configuration }} --no-restore --nologo
      - name: Test
        run: dotnet test -c ${{ matrix.configuration }} --no-build -v n --nologo