name: build

on:
  push:
    branches: [ main, github-actions ]
  pull_request:
    branches: [ main ]

jobs:
  sam-build:
    
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.8'
      - uses: aws-actions/setup-sam@v2
      - name: Configure AWS credentials from Test account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-duration-seconds: 900
          role-to-assume: arn:aws:iam::892601359836:role/github-action-role
          aws-region: us-east-1
  
  dotnet-build:
    
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [ '6.0.x' ]
        configuration: ['Debug', 'Release']

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build -c ${{ matrix.configuration }} --no-restore --nologo
      - name: Test
        run: dotnet test -c ${{ matrix.configuration }} --no-build -v n --nologo