name: deploy

on:
  push:
    branches: [ main ]

env:
  AWS_REGION : "us-east-1"

jobs:
  sam-deploy:

    needs: sam-build
    runs-on: ubuntu-latest
    permissions:
      id-token: write   # This is required for requesting the JWT
      contents: read    # This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'
      - uses: aws-actions/setup-sam@v2
        with:
          use-installer: true
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-duration-seconds: 900
          role-to-assume: arn:aws:iam::892601359836:role/github-action-role
          aws-region: ${{ env.AWS_REGION }}
      - run: sam build --parallel
      - run: sam deploy
